worker:
  itemMetaCustomAttributesJob:
    providers:
      mocaXp:
        enabled: true
        collection: "ETHEREUM:0x3a0e573f1e59ff6cea75d987cf73643e9f7feac6"
        baseUrl: "https://api-dev.mocaverse.xyz"
        uri: "/moca-xp/all_moca_xp.json"
