spring:
  data:
    mongodb:
      uri: mongodb://${mongodb.hosts}
      database: ${mongodb.database}
    elasticsearch:
      cluster-name: docker-cluster
      cluster-nodes: ${elasticsearch.cluster-nodes}

      client:
        reactive:
          endpoints:  ${elasticsearch.api-nodes}
          max-in-memory-size: 4194304
          socket-timeout: 30000
          connection-timeout: ${elasticsearch.timeout:120000}

  elasticsearch:
    rest:
      uris: ${elasticsearch.api-nodes}

  config:
    use-legacy-processing: true
    import: "consul:"
  cloud:
    bootstrap:
      enabled: true
