PUT _index_template/ownership_template

{
  "version": 1,

  "index_patterns": [
    "ownership_*"
  ],

  "template": {
    "aliases": {
      "order": {}
    },
    "mappings": {
      "properties": {
        "@timestamp": {
          "type": "date"
        },
        "ownershipId": {
          "type": "keyword"
        },
        "blockchain": {
          "type": "keyword",
          "ignore_above": 256
        },
        "itemId": {
          "type": "keyword"
        },
        "collection": {
          "type": "keyword",
          "ignore_above": 512
        },
        "value": {
          "type": "keyword"
        },
        "date": {
          "type": "date",
          "format": "strict_date_optional_time||epoch_millis"
        }
      }
    }
  }
}
