PUT _index_template/ownership_template

{
  "version": 1,

  "index_patterns": [
    "ownership_*"
  ],

  "template": {
    "aliases": {
      "order": {}
    },

    "mappings": {
      "properties": {
        "@timestamp": {
          "type": "date"
        },
        "ownershipId": {
          "type": "keyword"
        },
        "blockchain": {
          "type": "keyword"
        },
        "token": {
          "type": "keyword"
        },
        "tokenId": {
          "type": "keyword"
        },
        "itemId": {
          "type": "keyword"
        },
        "collection": {
          "type": "keyword"
        },
        "owner": {
          "type": "keyword"
        },
        "value": {
          "type": "keyword"
        },
        "date": {
          "type": "date"
        },
        "price": {
          "type": "keyword"
        },
        "priceUsd": {
          "type": "keyword"
        },
        "auctionEndDate": {
          "type": "date"
        },
        "orderSource": {
          "type": "keyword"
        }
      }
    }
  }
}
