spring:
  application:
    name: "union-meta-loader"

meta-loader:
  brokerReplicaSet: ${kafka.hosts}
  downloader:
    limits:
      - iterations: 50
        interval: "PT1M"
      - iterations: 100
        interval: "PT5M"
      - iterations: 200
        interval: "PT30M"
      - iterations: 500
        interval: "P1D"
