application:
  project: protocol

server:
  shutdown: graceful
  port: 8080

spring:
  application.name: union-meta-loader
  jackson:
    mapper:
      ACCEPT_CASE_INSENSITIVE_ENUMS: true
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false
    default-property-inclusion: non_null
  aop:
    proxy-target-class: false
  main:
    banner-mode: log
    web-application-type: reactive

rarible:
  core:
    apm:
      agent:
        enabled: true
        server: http://elk_apm-server:8200
        packages: com.rarible.protocol.union.meta.loader
      web:
        filter:
          enabled: false
      annotation:
        enabled: true
    client:
      name: rarible-protocol
  loader:
    broker-replica-set: ${kafka.hosts}
    topicsPrefix: protocol.${application.environment}.union.internal.loader
    enableNotifications: false
    enableWorkers: true
    enableRetrySchedulerJob: false
    workers: 4
    loadTasksBatchSize: 10
    retry:
      # Retry after 5m, 24h
      backoffDelaysMillis: [ 300000, 86400000 ]
      job:
        runner:
          period: 30000 # Schedule retry tasks every 30s

meta:
  ipfsGateway: "https://ipfs.io,https://nftstorage.link"
  ipfsPublicGateway: "https://ipfs.io"
  ipfsLegacyGateway: "https://rarible.mypinata.cloud"
  mediaFetchMaxSize: 131072 # 128 Kb
  openSeaProxyUrl: ${consul.meta.openSeaProxyUrl}
  http-client:
    type: ASYNC_APACHE # KTOR_APACHE, KTOR_CIO
    keep-alive: false
    thread-count: 1
    time-out: 10000
    total-connection: 1000

integration:
  ethereum:
    enabled: ${consul.ethereum.enabled:true}
    consumer:
      broker-replica-set: ${kafka.hosts}
      workers:
        item: 1
        ownership: 1
        order: 1
    auctionContracts: ${consul.ethereum.auctionContracts:}
  polygon:
    enabled: ${consul.polygon.enabled:true}
    consumer:
      broker-replica-set: ${kafka.hosts}
      workers:
        item: 1
        ownership: 1
        order: 1
    auctionContracts: ${consul.polygon.auctionContracts:}
  flow:
    enabled: ${consul.flow.enabled:true}
    consumer:
      broker-replica-set: ${kafka.hosts}
      workers:
        item: 1
        ownership: 1
        order: 1
    auctionContracts: ${consul.flow.auctionContracts:}
  tezos:
    enabled: ${consul.tezos.enabled:true}
    dipdup:
      network: ${consul.tezos.dipdup.network:}
      dipdupUrl: ${consul.tezos.dipdup.dipdupUrl:}
      nodeAddress: ${consul.tezos.dipdup.nodeAddress:}
      chainId: ${consul.tezos.dipdup.chainId:}
      sigChecker: ${consul.tezos.dipdup.sigChecker:}
      tzktUrl: ${consul.tezos.dipdup.tzktUrl:}
      ipfsUrl: ${consul.tezos.dipdup.ipfsUrl:"https://ipfs.io"}
      useDipDupTokens: ${consul.tezos.dipdup.useDipDupTokens:false}
      useDipDupRoyalty: ${consul.tezos.dipdup.useDipDupRoyalty:false}
      knownAddresses:
        hen: ${consul.tezos.dipdup.knownAddresses.hen:}
        henRoyalties: ${consul.tezos.dipdup.knownAddresses.henRoyalties:}
        kalamint: ${consul.tezos.dipdup.knownAddresses.kalamint:}
        fxhashV1: ${consul.tezos.dipdup.knownAddresses.fxhashV1:}
        fxhashV1Manager: ${consul.tezos.dipdup.knownAddresses.fxhashV1Manager:}
        fxhashV2: ${consul.tezos.dipdup.knownAddresses.fxhashV2:}
        versum: ${consul.tezos.dipdup.knownAddresses.versum:}
        royaltiesManager: ${consul.tezos.dipdup.knownAddresses.royaltiesManager:}
        bidou8x8: ${consul.tezos.dipdup.knownAddresses.bidou8x8:}
        bidou24x24: ${consul.tezos.dipdup.knownAddresses.bidou24x24:}
        dogami: ${consul.tezos.dipdup.knownAddresses.dogami:}
        dogamiGap: ${consul.tezos.dipdup.knownAddresses.dogamiGap:}
        dogamiStar: ${consul.tezos.dipdup.knownAddresses.dogamiStar:}
      consumer:
        broker-replica-set: ${consul.tezos.dipdup.consumer.hosts:}
        username: ${consul.tezos.dipdup.consumer.username:}
        password: ${consul.tezos.dipdup.consumer.password:}
        workers:
          order: 1
          activity: 1
    client:
      url: ${consul.tezos.api.baseUrl}
    consumer:
      broker-replica-set: ${consul.tezos.kafka.hosts}
      username: ${consul.tezos.kafka.username}
      password: ${consul.tezos.kafka.password}
      workers:
        item: 1
        ownership: 1
        order: 1
    auctionContracts: ${consul.tezos.auctionContracts:}
  solana:
    enabled: ${consul.solana.enabled:false}
  immutablex:
    enabled: ${consul.immutablex.enabled:true}
    client:
      url: ${consul.immutablex.api.baseUrl:}
      byIdsChunkSize: 16
    apiKey: ${consul.immutablex.api.key:}

#  Not needed in the meta-loader module. Transitive dependency onto the "core" module
common:
  producer:
    broker-replica-set: ${kafka.hosts}

meta-loader:
  brokerReplicaSet: ${kafka.hosts}
  downloader:
    item:
      event:
        workers: 3
        batchSize: 16
        poolSize: 4
      api:
        workers: 3
        batchSize: 16
        poolSize: 4
      refresh:
        workers: 3
        batchSize: 8
        poolSize: 2
      retry:
        workers: 3
        batchSize: 8
        poolSize: 2
      sync:
        workers: 3
        batchSize: 8
        poolSize: 2

# Disable verbose logs of Apache HTTP client used to load content media metadata.
logging:
  level:
    org.apache.http: ERROR
