spring:
  application:
    name: "union-meta-loader"

integration:
  ethereum:
    enabled: ${consul.ethereum.enabled:true}
    consumer:
      broker-replica-set: ${kafka.hosts}
      workers:
        item: 1
        ownership: 1
        order: 1
    auctionContracts: ${consul.ethereum.auctionContracts:}
  polygon:
    enabled: ${consul.polygon.enabled:true}
    consumer:
      broker-replica-set: ${kafka.hosts}
      workers:
        item: 1
        ownership: 1
        order: 1
    auctionContracts: ${consul.polygon.auctionContracts:}
  mantle:
    enabled: ${consul.mantle.enabled:false}
    consumer:
      broker-replica-set: ${kafka.hosts}
      workers:
        item: 1
        ownership: 1
        order: 1
    auctionContracts: ${consul.mantle.auctionContracts:}
  flow:
    enabled: ${consul.flow.enabled:true}
    consumer:
      broker-replica-set: ${kafka.hosts}
      workers:
        item: 1
        ownership: 1
        order: 1
    auctionContracts: ${consul.flow.auctionContracts:}
  tezos:
    enabled: ${consul.tezos.enabled:true}
    dipdup:
      network: ${consul.tezos.dipdup.network:}
      dipdupUrl: ${consul.tezos.dipdup.dipdupUrl:}
      dipdupToken: ${consul.tezos.dipdup.dipdupToken:}
      nodeAddress: ${consul.tezos.dipdup.nodeAddress:}
      chainId: ${consul.tezos.dipdup.chainId:}
      sigChecker: ${consul.tezos.dipdup.sigChecker:}
      tzktUrl: ${consul.tezos.dipdup.tzktUrl:}
      ipfsUrl: ${consul.tezos.dipdup.ipfsUrl:"https://ipfs.io"}
      useDipDupTokens: ${consul.tezos.dipdup.useDipDupTokens:false}
      useDipDupRoyalty: ${consul.tezos.dipdup.useDipDupRoyalty:false}
      saveDipDupRoyalty: ${consul.tezos.dipdup.saveDipDupRoyalty:false}
      enrichDipDupCollection: ${consul.tezos.dipdup.enrichDipDupCollection:true}
      knownAddresses:
        hen: ${consul.tezos.dipdup.knownAddresses.hen:}
        henRoyalties: ${consul.tezos.dipdup.knownAddresses.henRoyalties:}
        kalamint: ${consul.tezos.dipdup.knownAddresses.kalamint:}
        fxhashV1: ${consul.tezos.dipdup.knownAddresses.fxhashV1:}
        fxhashV1Manager: ${consul.tezos.dipdup.knownAddresses.fxhashV1Manager:}
        fxhashV2: ${consul.tezos.dipdup.knownAddresses.fxhashV2:}
        versum: ${consul.tezos.dipdup.knownAddresses.versum:}
        royaltiesManager: ${consul.tezos.dipdup.knownAddresses.royaltiesManager:}
        bidou8x8: ${consul.tezos.dipdup.knownAddresses.bidou8x8:}
        bidou24x24: ${consul.tezos.dipdup.knownAddresses.bidou24x24:}
        dogami: ${consul.tezos.dipdup.knownAddresses.dogami:}
        dogamiGap: ${consul.tezos.dipdup.knownAddresses.dogamiGap:}
        dogamiStar: ${consul.tezos.dipdup.knownAddresses.dogamiStar:}
      consumer:
        broker-replica-set: ${consul.tezos.dipdup.consumer.hosts:}
        username: ${consul.tezos.dipdup.consumer.username:}
        password: ${consul.tezos.dipdup.consumer.password:}
        workers:
          order: 1
          activity: 1
    client:
      url: ${consul.tezos.api.baseUrl}
    consumer:
      broker-replica-set: ${consul.tezos.kafka.hosts}
      username: ${consul.tezos.kafka.username}
      password: ${consul.tezos.kafka.password}
      workers:
        item: 1
        ownership: 1
        order: 1
    auctionContracts: ${consul.tezos.auctionContracts:}
  solana:
    enabled: ${consul.solana.enabled:false}
  immutablex:
    enabled: ${consul.immutablex.enabled:true}
    client:
      url: ${consul.immutablex.api.baseUrl:}
      byIdsChunkSize: 16
    clientV3:
      url: ${consul.immutablex.api.baseUrlV3:}
      byIdsChunkSize: 16
    apiKey: ${consul.immutablex.api.key:}

meta-loader:
  brokerReplicaSet: ${kafka.hosts}
  downloader:
    limits:
      - iterations: 50
        interval: "PT1M"
      - iterations: 100
        interval: "PT5M"
      - iterations: 200
        interval: "PT30M"
      - iterations: 500
        interval: "P1D"
