meta-loader:
  downloader:
    # Since we have 1024 connection pool size per API client and 2*pool size batch for mongo pipeline processing,
    # we should have 1024/2 total size of all connection pools
    item:
      event:
        poolSize: 256
      api:
        poolSize: 32
      refresh:
        poolSize: 96
      retry:
        poolSize: 96
      retry_partial:
        poolSize: 16
      sync:
        poolSize: 16
